language: node_js
node_js:
  - "node"
script:
  - npm run build
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/959b6c4ba0ff71ae8b43
    on_success: change
    on_failure: always
    on_start: never
